### ISSUE TITLE
User Auth Checklist

### ISSUE THREAD

**Issue by FarahYQ** [FarahYQ/LiftOff#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [ ] Styling
  - [ ] When errors are displayed, the input boxes should not move
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
  - [x] Errors should display for both `/signup` and`/login`.
  - [x] Errors should clear when moving between `/signup` and `/login`.
  - [x] Add `cursor: pointer` all your buttons and navlinks!
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by FarahYQ** [comment]
Got everything to work except that the errors move the input boxes slightly.

**Comment by xnanodax** [comment]
We may need to place the errors rendered in a div or some html element that has a pre-defined height :)
